### ISSUE TITLE
`Authorization code grant`   NoClassDefFoundError: com/sun/net/httpserver/HttpServer and no token fetched 

### ISSUE THREAD

**Issue by YoranSys** [warmuuh/milkman#103]
Hi,
When we hit `Fetch token` with an `Authorization code grant` there is an error NoClassDefFoundError: com/sun/net/httpserver/HttpServer and no token is fetched. 

```java
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/net/httpserver/HttpServer
	at milkman.plugin.auth.oauth.server.AuthorizationCodeCaptureServer.<init>(AuthorizationCodeCaptureServer.java:27)
	at milkman.plugin.auth.oauth.model.Oauth2Api.lambda$authenticationCodeGrant$3(Oauth2Api.java:52)
	at milkman.plugin.auth.oauth.model.Oauth2Api.getToken(Oauth2Api.java:73)
	at milkman.plugin.auth.oauth.model.Oauth2Api.authenticationCodeGrant(Oauth2Api.java:51)
	at milkman.plugin.auth.oauth.model.Oauth2Grant$AuthorizationCodeGrant.getToken(Oauth2Grant.java:45)
	at milkman.plugin.auth.oauth.model.Oauth2Credentials.fetchNewToken(Oauth2Credentials.java:83)
	at milkman.plugin.auth.oauth.Oauth2KeyEditor.fetchToken(Oauth2KeyEditor.java:109)
	at milkman.plugin.auth.oauth.Oauth2KeyEditor.lambda$getRoot$3(Oauth2KeyEditor.java:80)
	at milkman.utils.fxml.FxmlBuilder.lambda$button$0(FxmlBuilder.java:29)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
...
Caused by: java.lang.ClassNotFoundException: com.sun.net.httpserver.HttpServer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 207 more
```

OS: Linux
Version : 5.2.0

**Comment by warmuuh** [comment]
should be fixed in nighly. will be released with next version
