### ISSUE TITLE
milkman-grpc Finding exe executeable on Linux

### ISSUE THREAD

**Issue by segadora** [warmuuh/milkman#132]
I am having a problem with the grpc plugin, it seems like it looks for a windows executeable on linux.
Can I workaround this?

```
protoc-jar: protoc version: 3.8.0, detected platform: linux-x86_64 (linux/amd64)
protoc-jar: embedded: bin/3.8.0/protoc-3.8.0-linux-x86_64.exe
protoc-jar: executing: [/tmp/protocjar16718876374982093493/bin/protoc.exe, /tmp/temp9987384456767459004.proto, -I/tmp, -I/tmp/protocjar16718876374982093493/include, --descriptor_set_out=/tmp/descriptor6900064993171441939.pb.bin, --include_imports]
temp9987384456767459004.proto:68:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
temp9987384456767459004.proto:83:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
09:36:39.254 [Thread-10] WARN me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker - Protoc invocation failed with status: 1
09:36:39.254 [Thread-10] WARN me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker - [Protoc log] 
09:36:39.254 [Thread-10] ERROR milkman.ctrl.RequestExecutor - Execution of request failed
me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[/tmp/temp9987384456767459004.proto, -I/tmp, --include_std_types, --descriptor_set_out=/tmp/descriptor6900064993171441939.pb.bin, --include_imports]]
	at me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:121)
	at me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:62)
	at milkman.plugin.grpc.processor.GrpcRequestProcessor.compileProtoSchema(GrpcRequestProcessor.java:136)
	at milkman.plugin.grpc.processor.GrpcRequestProcessor.makeRequest(GrpcRequestProcessor.java:83)
	at milkman.plugin.grpc.processor.GrpcRequestProcessor.executeRequest(GrpcRequestProcessor.java:41)
	at milkman.plugin.grpc.GrpcPlugin.executeRequestAsync(GrpcPlugin.java:81)
	at milkman.ctrl.RequestExecutor$1.call(RequestExecutor.java:47)
	at milkman.ctrl.RequestExecutor$1.call(RequestExecutor.java:29)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Service.java:725)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by segadora** [comment]
After poking the code a bit, I think the issue is in https://github.com/os72/protoc-jar

**Comment by warmuuh** [comment]
i am not 100% sure but although the log is saying `protoc-3.8.0-linux-x86_64.exe`, it is no windows executable, it is a linux one. i think, the real error here is 
```
temp9987384456767459004.proto:68:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
temp9987384456767459004.proto:83:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```
