### ISSUE TITLE
App does not show up in Linux

### ISSUE THREAD

**Issue by walec51** [warmuuh/milkman#33]
Just tested 3.7.0 on Fedora 31 (Gnome 3). No app window showed up. Got this in console:

```
$ ./milkman.sh 
11:51:42.658 [main] INFO milkman.MilkmanApplication - VM Startup time: 322 ms
java.lang.UnsupportedOperationException: Taskbar API is not supported on the current platform
	at java.desktop/java.awt.Taskbar.getTaskbar(Taskbar.java:216)
	at milkman.ui.main.MainWindow.setIcon(MainWindow.java:98)
	at milkman.ui.main.MainWindow.start(MainWindow.java:62)
	at milkman.MilkmanApplication.start(MilkmanApplication.java:43)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:51:43.123 [JavaFX Application Thread] INFO milkman.ctrl.WorkspaceController - Diplaying request: RequestContainer(name=New Request)
11:51:43.370 [JavaFX Application Thread] INFO milkman.ui.main.WorkingAreaComponent - tab repainted
11:51:43.370 [JavaFX Application Thread] INFO milkman.ui.main.WorkingAreaComponent - request area refreshed
11:51:43.993 [JavaFX Application Thread] INFO milkman.MilkmanApplication - App Initialization time: 1333 ms
11:51:44.167 [Thread-5] INFO milkman.cds.AppCdsGenerator - AppCds archive is up-to-date and usable. Not regenerating.

```

**Comment by warmuuh** [comment]
oh, thanks,  (java is platform-independent... best joke ever).
will fix within 24h
