### ISSUE TITLE
EOF reached while reading

### ISSUE THREAD

**Issue by gauravn00b** [warmuuh/milkman#83]
Getting below error while executing HTTP request. Also, please advice how to send HTTP2 request, seems no option coming.

2021-01-14 12:31:59,019 ERROR [elastic-3] m.u.p.r.ResponseBodyTabController [ResponseBodyTabController.java:59] Received Error
java.io.EOFException: EOF reached while reading
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:591)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:632)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)

**Comment by warmuuh** [comment]
milkman does support Http2 requests (just verified via https://http2.pro/api/v1, compare to `curl --http2 https://http2.pro/api/v1`). please verify that you have `options->http->http2 enabled` switched on.
you can see the protocol used in the status bar of the response:
![image](https://user-images.githubusercontent.com/1331628/104577240-877b1280-5659-11eb-8e55-54183b6702ea.png)


regarding the exception: this might be indicating some issue with the server not responding correctly (http1 maybe or just nothing). normally, http2 is just working fine.

**Comment by gauravn00b** [comment]
Thanks for the reply. HTTP2 is indeed enabled:

![image](https://user-images.githubusercontent.com/70876227/104591188-5965f480-5692-11eb-8972-aea333864f7d.png)

However, im trying to send POST from Milkman as below:

![image](https://user-images.githubusercontent.com/70876227/104591295-7a2e4a00-5692-11eb-9048-d9b19347f3ec.png)

However, on server, received HTTP 1.1, instead of HTTP2:

![image](https://user-images.githubusercontent.com/70876227/104591123-45ba8e00-5692-11eb-8b9e-b0a5c7b42561.png)

any help will be much appreciated. Thanks.

**Comment by gauravn00b** [comment]
Further checked, it seems Milkman is sending connection upgrade. is it possible to send direct http2 (like http2-prior-knowledge) instead of connection upgrade?

![image](https://user-images.githubusercontent.com/70876227/104592665-90d5a080-5694-11eb-8de2-67e5a67165be.png)

**Comment by warmuuh** [comment]
ah, got you.. i will look into this when i find some time. first research though might be a bit disappointing (https://stackoverflow.com/questions/52513932/force-immediate-insecure-http2-connection-with-java-httpclient) as it looks like it is not supported. if you want to give it a try, [this](https://github.com/warmuuh/milkman/blob/master/milkman-rest/src/main/java/milkman/ui/plugin/rest/JavaRequestProcessor.java#L69) is the place to look at

**Comment by gauravn00b** [comment]
sure. Thank You

**Comment by warmuuh** [comment]
i did some investigation and on plain java11, it is not possible tho it may be implemented in future JDKs (could not find a bug tracing this though).
On the other hand does netty support this (see https://github.com/netty/netty/issues/9733). so in theory, to support this feature, a reimplementation of `milkman.ui.plugin.rest.RequestProcessor` on top of netty would be needed which is too much work to just support this small feature. it also bloats the (very slim) rest-plugin with netty-dependency (which is in no way lightweight).
what you could do is to create a new plugin similar to the graphql-plugin, which is a very slim wrapper around the rest-plugin, reusing the same requestProcessor. here, you could use your custom RequestProcessor. 
if you actually want to go ahead we could also talk about allowing to extend (via plugins) the RequestProcessor so that a user can choose an "enigne" to execute rest-calls in the options.

because i wont spend any more time on this, i will close the bug for now
